### ISSUE TITLE
Fix bug: when uploading a pdf to content page.

### ISSUE THREAD

**Issue by j-nakashima** [lepo-project/lepo#116]
To fix a bug that occurs in the following cases.
1. Upoad a single page pdf.
  -> [filename].pdf is created.

2. Upload a multi pages pdf to update.
  -> [filename]_p1.pdf, [filename]_p2.pdf , ... are created.
      but  [filename].pdf that can't be read is left.

**Comment by kyoshizaki** [comment]
Thanks for your commit.
Now I have merged it to master branch.

**Comment by kyoshizaki** [comment]
To fix a bug that occurs in the following cases.

Upload a single page pdf as PageFile.
-> [filename].pdf is created.

Upload a multi pages pdf as AssetFile to update PageFile.
-> error

**Comment by kyoshizaki** [comment]
Done!
