### ISSUE TITLE
Rethink emojis in .commit_template

### ISSUE THREAD

**Issue by kyoshizaki** [lepo-project/lepo#31]
Emojis in the commit message are displayed differently depending on the OS and browser.
Especially bugs in  MS and Google OS are similar to the real bugs and make me feel bad...
<img width="869" alt="2017-08-22 20 36 21" src="https://user-images.githubusercontent.com/176555/29570807-7ee47a60-8792-11e7-893d-5184d47e1cbf.png">

**Comment by j-nakashima** [comment]
How about using 🔨  or 🔧 when fixing a bug,
and use  🐛 when finding a bug. 
 🔨  and 🔧  are sometimes used for minor fix for a bug.
Or using [fix], [new], instead of emoji...

**Comment by kyoshizaki** [comment]
🔧 seems much better than 🐛 for fixing a bug.
Thanks!
