### ISSUE TITLE
English notation for date and time

### ISSUE THREAD

**Issue by kyoshizaki** [lepo-project/lepo#4]
Now date and time is only shown in Japanese (with Chinese character), so use correct language file in /config/locales folder to show those info.

**Comment by j-nakashima** [comment]
Can I get some suggestions ?

There are 5 formats of 'date and time',  now (  'ymdhm', 'md','mdhm','mdh','md' ).
But it seems that 'mdh' and 'md' are not used.
So, is this okay to replace these format's keywords with default date time format's keywords ('default', 'long','short'). 
 ('%-m月%-d日%H:%M'):'mdhm' -> default
 ('%Y年%-m月%-d日'):'ymd' -> short,
 ('%Y年%-m月%-d日%H:%M'):'ymdhm' -> long

Or is it better to add original 5 formats to locale file?

**Comment by j-nakashima** [comment]
[ja.yml] 

(Pan A)
  time:
    am: 午前
    formats:
      default: "%-m月%-d日%H:%M"
      long: "%Y年%-m月%-d日%H:%M"
      short: "%Y年%-m月%-d日"
    pm: 午後

(Plan B)
  time:
    am: 午前
    formats:
      default: "%Y/%m/%d %H:%M:%S"
      long: "%Y年%m月%d日(%a) %H時%M分%S秒 %z"
      short: "%y/%m/%d %H:%M"
      ymdhm: "%Y年%-m月%-d日%H:%M"
      ymd: "%Y年%-m月%-d日"
      mdhm: "%-m月%-d日%H:%M"
      mdh: "%-m月%-d日%H時"
      md: "%-m月%-d日"
    pm: 午後

**Comment by kyoshizaki** [comment]
Hi,
I think default date time format is good enough, so please code with Plan A.
Thanks!

**Comment by j-nakashima** [comment]
I agree. Thank you.
